In [1]:
import pandas as pd

In [35]:
df = pd.read_csv("Data.csv")
df

,Reference number,Source,Description of Incidents,Type of Attack,Attempted or Raped,Who was it reported to,Consequences of the attack,Date of Incident,Districts,Geographical Region
0,CH14QV99NQ,http://thehimalayantimes.com/fullNews.php?head...,An 18-year-old youth was arrested March 25 on ...,Child,Molesting,Victim Father,Physical Injury,25/03/2013,Kathmandu,"27.7199745185167, 85.32344429728326"
1,XJ99BF74EC,http://nepalpolice.gov.np/%E0%A4%9C%E0%A4%B5%E...,Police had taken under control Hitman Shahi (4...,Child,Attempted,Police,Physical Injury,03/04/2013,Kathmandu,"27.7199745185167, 85.32344429728326"
2,IG49WH92XY,http://nepalpolice.gov.np/2013-05-02-10-32-36....,Fourteen year old Devendra Rana and eleven yea...,Gang,Raped,Police,Physical Injury,01/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326"
3,IS62NJ41RL,http://nepalpolice.gov.np/2013-05-07-10-39-08....,Police on 07 May arrested Dharmaraj Jamarkatte...,Child,Raped,Police,Physical Injury,07/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326"
4,ZP39BS50LY,http://thehimalayantimes.com/fullNews.php?head...,Police on 08 May arrested Bhakta Bahadur Blon ...,Opportunist,Raped,Police,Physical Injury,08/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326"
...,...,...,...,...,...,...,...,...,...,...
2415,VQ02QJ16IA,https://nepalmonitor.org/reports/view/41875,One person has been arrested on charges of rap...,Opportunist,Rape,Police,Physical Injury,14/06/2023,Lalitpur,"27.662405818404125, 85.32435296718468"
2416,OS92RX27HN,https://nepalpolice.gov.np/news/3741/,"Baglung, a 17-year-old boy living in Nisikhola...",Child,Rape,Police,Physical Injury,09/07/2023,Baglung,"28.28119980900559, 83.58164488651326"
2417,LW75CB63DB,https://nepalpolice.gov.np/news/3746/,"Jhapa, 31-year-old Dhan Kumar Limbu, resident ...",Opportunist,Rape,Police,Physical Injury,07/02/2023,Jhapa,"26.577739181619766, 87.89718581504616"
2418,KH48LW89IO,https://nepalpolice.gov.np/news/3767/,"Baglung, Police arrested 28-year-old Bimal Ham...",Opportunist,Rape,Police,Physical Injury,12/07/2023,Baglung,"28.28104863825078, 83.58215987061996"
2419,HH53FD93DS,https://nepalmonitor.org/reports/view/41911,Man arrested from Sankhuwasabha on the charge ...,Opportunist,Rape,Police,Physical Injury,12/07/2023,Sankhuwasabha,"27.676079840209752, 87.30574864049214"

In [36]:
df["Sources"] = df['Source'].str.extract(r'[/(]([\w.]+)')

In [37]:
df

,Reference number,Source,Description of Incidents,Type of Attack,Attempted or Raped,Who was it reported to,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
0,CH14QV99NQ,http://thehimalayantimes.com/fullNews.php?head...,An 18-year-old youth was arrested March 25 on ...,Child,Molesting,Victim Father,Physical Injury,25/03/2013,Kathmandu,"27.7199745185167, 85.32344429728326",thehimalayantimes.com
1,XJ99BF74EC,http://nepalpolice.gov.np/%E0%A4%9C%E0%A4%B5%E...,Police had taken under control Hitman Shahi (4...,Child,Attempted,Police,Physical Injury,03/04/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
2,IG49WH92XY,http://nepalpolice.gov.np/2013-05-02-10-32-36....,Fourteen year old Devendra Rana and eleven yea...,Gang,Raped,Police,Physical Injury,01/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
3,IS62NJ41RL,http://nepalpolice.gov.np/2013-05-07-10-39-08....,Police on 07 May arrested Dharmaraj Jamarkatte...,Child,Raped,Police,Physical Injury,07/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
4,ZP39BS50LY,http://thehimalayantimes.com/fullNews.php?head...,Police on 08 May arrested Bhakta Bahadur Blon ...,Opportunist,Raped,Police,Physical Injury,08/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",thehimalayantimes.com
...,...,...,...,...,...,...,...,...,...,...,...
2415,VQ02QJ16IA,https://nepalmonitor.org/reports/view/41875,One person has been arrested on charges of rap...,Opportunist,Rape,Police,Physical Injury,14/06/2023,Lalitpur,"27.662405818404125, 85.32435296718468",nepalmonitor.org
2416,OS92RX27HN,https://nepalpolice.gov.np/news/3741/,"Baglung, a 17-year-old boy living in Nisikhola...",Child,Rape,Police,Physical Injury,09/07/2023,Baglung,"28.28119980900559, 83.58164488651326",nepalpolice.gov.np
2417,LW75CB63DB,https://nepalpolice.gov.np/news/3746/,"Jhapa, 31-year-old Dhan Kumar Limbu, resident ...",Opportunist,Rape,Police,Physical Injury,07/02/2023,Jhapa,"26.577739181619766, 87.89718581504616",nepalpolice.gov.np
2418,KH48LW89IO,https://nepalpolice.gov.np/news/3767/,"Baglung, Police arrested 28-year-old Bimal Ham...",Opportunist,Rape,Police,Physical Injury,12/07/2023,Baglung,"28.28104863825078, 83.58215987061996",nepalpolice.gov.np
2419,HH53FD93DS,https://nepalmonitor.org/reports/view/41911,Man arrested from Sankhuwasabha on the charge ...,Opportunist,Rape,Police,Physical Injury,12/07/2023,Sankhuwasabha,"27.676079840209752, 87.30574864049214",nepalmonitor.org

Data cleaning took way longer then expected. Mostly the sources column. There were about 12+ different formats in which website or sources were stored and bringing them into a common representation was a huge task.

***
<b>Below are the unique sources extracted from all of the datasets.</b>

In [73]:
df[df["Sources"] =='com']

,Reference number,Description of Incidents,Type of Attack,Attempted or Raped,Reported To,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
45,HF99GL41DO,Police on 25 April made public four persons in...,gang,assault,police,physical injury,25/04/2014,rautahat,"28.12114330422753, 82.85604885535905",com
57,AK42MD51TF,"Purna Bahadur Gurung, 68, of Angding-9 of the ...",opportunist,assault,neighbours,physical injury,26/05/2014,terhathum,"26.63000151740098, 87.1814830251505",com
63,ZI10TP04HR,An 11-year-old girl was raped at her house in ...,minor,assault,police,physical injury,13/07/2014,kailali,"28.023616335136484, 83.80435180034958",com
66,DB70JU37ZS,"Police have arrested Dhan Bahadur Gurung, 23,...",minor,assault,police,physical injury,21/07/2014,gorkha,"28.839299762331823, 80.32165271565319",com
77,SD10BF49QT,"Police had arrested Pradip Shankar, 17, of Lu...",minor,assault,police,physical injury,17/08/2014,panchthar,"28.00405562156679, 82.47475950014869",com
87,PB66OG02YD,A woman was reportedly gang-raped inside a tru...,opportunist,assault,police,physical injury,13/09/2014,sunsari,"27.948035024085737, 84.22564678589721",com
93,WX60UF72IU,A 17-year-old girl has been raped in the distr...,opportunist,assault,police,physical injury,24/09/2014,illam,"27.55782556751356, 85.02231481154203",com
95,HH99UV08OX,A ten-year-old girl was allegedly raped at Pip...,minor,assault,relatives,physical injury,03/10/2014,rautahat,"28.002539987988857, 82.47441617741089",com
96,WY95FH37RG,A 14-year old Indian girl who was at her relat...,gang,assault,police,physical injury,07/10/2014,siraha,"26.95732550711719, 85.31465054202445",com
97,FD42QU03NW,A 19-year old girl of Majhouliya VDC-8 in the ...,gang,assault,police,physical injury,08/10/2014,siraha,"26.644031159993535, 86.18654780032634",com
107,TI72SK91PP,"Dirgha Prasad Sherchan, a constable of the Arm...",opportunist,assault,police,physical injury,24/10/2014,baglung,"27.72058235705603, 85.32447426549668",com
112,LR20LR46HA,Police on 29 October had arrested an alleged r...,minor,assault,family,physical injury,29/10/2014,morang,"27.18716614524141, 86.78270938290953",com
115,XD47PV19SF,A group of local youths gang-raped an Indian w...,gang,assault,police,physical injury,02/12/2014,bara,"27.946366959914478, 84.22736339958624",com
118,RE68HZ64GP,Two youths had been arrested on charge of alle...,gang,assault,police,physical injury,13/12/2014,sindhupalchowk,"28.003146243978502, 82.47647611383772",com
127,BT76TO31BJ,A teenager was arrested on the charge of rapin...,minor,assault,mother,physical injury,14/01/2015,gorkha,"28.37786381764818, 84.85758227612041",com
132,CO25SY20SQ,A woman was gang raped at Punarbas Municipalit...,gang,assault,police,physical injury,15/02/2015,kanchanpur,"28.878499063201645, 80.3212652521494",com
134,GR64MS48IW,The daughter of a low-key merchant was raped b...,minor,assault,family,physical injury,20/02/2015,bara,"27.17254015291334, 85.06705293133683",com
146,FS40SD50EV,A woman had been gang-raped in Rautahat distri...,gang,assault,police,physical injury,23/06/2015,rautahat,"26.996372610061584, 85.31008542893395",com
149,KI06IB21JN,RAUTAHAT: A minor girl has been raped at Patau...,minor,assault,police,physical injury,02/08/2015,rautahat,"26.992701598054346, 85.3142053017876",com
176,BJ44SL83NQ,A four years old girl was raped in Rapla VDC o...,minor,assault,family,physical injury,27/10/2015,darchula,"30.010647662788543, 80.90373185962632",com
178,LM13LG05RQ,Mahottari Police had arrested 35-year-old Pada...,opportunist,assault,police,physical injury,27/10/2015,mahottari,"26.918412241915775, 85.80236068834819",com
194,HV64DB19RL,Police on 18 November had paraded three people...,gang,assault,police,murder,23/11/2015,surkhet,"28.592708349825443, 81.78517635638165",com
217,PC69RP47FJ,Police had arrested two people on the charge o...,gang,assault,family,physical injury,03/01/2016,sunsari,"26.667044357556872, 87.18101719413106",com
273,WI46LF84QS,Police had arrested a 15-year-old boy on the c...,minor,assault,family,physical injury,05/04/2016,dang,"28.079252696688677, 82.47789156839599",com
280,FJ43OM22ID,An eight year-old girl was raped and consequen...,minor,assault,police,murder,19/04/2016,palpa,"27.905257679916733, 83.63226558276523",com
355,OR17MN25UY,Police had arrested 18-year-old Babin Rai of K...,minor,assault,police,physical injury,03/08/2016,khotang,"27.22613660805549, 86.77843586212428",com
360,OA05DG72WS,Police on 09 August midnight had arrested a fi...,opportunist,attempt,police,physical injury,09/08/2016,kathmandu,"27.72763410311441, 85.32372709254854",com
363,QT64MC10JU,Police 14 August had arrested Singha Bahadur R...,opportunist,assault,police,physical injury,14/08/2016,khotang,"27.224915460347304, 86.78118244402673",com
366,PT82LK20ZF,A girl had been raped in her rented room at Ne...,minor,assault,police,physical injury,21/08/2016,banke,"28.139650156461023, 81.82429211694577",com
368,AJ37IC32TT,A 20-year-old girl had been gang-raped at arou...,gang,assault,police,physical injury,23/08/2016,banke,"28.142072067000196, 81.82154553504333",com
390,DJ15IC31ZC,Nepal Police has intensified search for four m...,gang,assault,police,physical injury,15/11/2016,kathmandu,"27.72763410311441, 85.32407041528634",com
423,IQ05TI48BL,Police have arrested a man on the charge of ra...,opportunist,assault,police,physical injury,21/03/2017,solukhumbu,"27.73919001822685, 86.74040619082075",com
496,YV07CB72TI,A man was arrested on rape charges from Bhojpu...,opportunist,assault,police,physical injury,17/10/2017,bhojpur,"27.2265941635556, 87.10427952252019",com
502,XZ88MD05QK,Chitwan Police have arrested two people on th...,gang,assault,police,physical injury,26/10/2017,chitwan,"27.609673180394033, 84.34921080762804",com

In [39]:
df["Sources"].unique()

array(['thehimalayantimes.com', 'nepalpolice.gov.np', 'com',
       'ekantipur.com', nan, 'nepalnews.com', 'new.com',
       'nepalmonitor.org', 'inseconline.org', 'nagariknetwork.com',
       'annapurnapost.com', 'onlinekhabar.com', 'ratopati.com',
       'myrepublica.com', 'ujyaaloonline.com', 'en', 'drive.google.com',
       'khabarhub.com', 'rajdhanidaily.com', 'spotlightnepal.com',
       'nepalipolice.gov.np', 'dineshkhabar.com', 'koshionline.com',
       'nepalpolice.com.np', 'nayapatrikadaily.com', 'blastkhabar.com',
       'kharibot.com', 'setopati.com', 'newsofnepal.com', 'nepalpati.com',
       'news24nepal.tv', 'thahakhabar.com', 'saurahaonline.com',
       'khabarbreak.com', 'thepublictoday.com', 'pahilopost.com',
       'imagekhabar.com', 'baahrakhari.com', 'enewsbureau.com',
       'nepallive.com', 'accounts.google.com', 'khabarcenter.com',
       'nepalkhabar.com', 'nepalpress.com', 'setokhari.com',
       'sajilopost.com', 'kathmandupress.com', 'deshsanchar.com',
       'pokharanews.com', 'ejanakpurtoday.com', 'gorkhapatraonline.com',
       'kantipath.com'], dtype=object)

Remove the original source column

In [40]:
df = df.drop('Source',axis = 1)

In [41]:
df

,Reference number,Description of Incidents,Type of Attack,Attempted or Raped,Who was it reported to,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
0,CH14QV99NQ,An 18-year-old youth was arrested March 25 on ...,Child,Molesting,Victim Father,Physical Injury,25/03/2013,Kathmandu,"27.7199745185167, 85.32344429728326",thehimalayantimes.com
1,XJ99BF74EC,Police had taken under control Hitman Shahi (4...,Child,Attempted,Police,Physical Injury,03/04/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
2,IG49WH92XY,Fourteen year old Devendra Rana and eleven yea...,Gang,Raped,Police,Physical Injury,01/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
3,IS62NJ41RL,Police on 07 May arrested Dharmaraj Jamarkatte...,Child,Raped,Police,Physical Injury,07/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
4,ZP39BS50LY,Police on 08 May arrested Bhakta Bahadur Blon ...,Opportunist,Raped,Police,Physical Injury,08/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",thehimalayantimes.com
...,...,...,...,...,...,...,...,...,...,...
2415,VQ02QJ16IA,One person has been arrested on charges of rap...,Opportunist,Rape,Police,Physical Injury,14/06/2023,Lalitpur,"27.662405818404125, 85.32435296718468",nepalmonitor.org
2416,OS92RX27HN,"Baglung, a 17-year-old boy living in Nisikhola...",Child,Rape,Police,Physical Injury,09/07/2023,Baglung,"28.28119980900559, 83.58164488651326",nepalpolice.gov.np
2417,LW75CB63DB,"Jhapa, 31-year-old Dhan Kumar Limbu, resident ...",Opportunist,Rape,Police,Physical Injury,07/02/2023,Jhapa,"26.577739181619766, 87.89718581504616",nepalpolice.gov.np
2418,KH48LW89IO,"Baglung, Police arrested 28-year-old Bimal Ham...",Opportunist,Rape,Police,Physical Injury,12/07/2023,Baglung,"28.28104863825078, 83.58215987061996",nepalpolice.gov.np
2419,HH53FD93DS,Man arrested from Sankhuwasabha on the charge ...,Opportunist,Rape,Police,Physical Injury,12/07/2023,Sankhuwasabha,"27.676079840209752, 87.30574864049214",nepalmonitor.org

In [42]:
df['Consequences of the attack'].unique()

array(['Physical Injury ', 'Physical injury ', 'Physical injury',
       'Mantally ill', 'Murder', 'Physical Injury', 'Pregnant',
       'physical Injury', 'pregnant ', 'Dearth', 'Murdered',
       'Physical Attack', 'Muder', ' pregnent', 'pregnant', nan,
       ' Physical Injury ', ' Murdered'], dtype=object)

In [46]:
df['Consequences of the attack'] = df['Consequences of the attack'].str.lower()
df['Consequences of the attack'] = df['Consequences of the attack'].str.strip()

In [47]:
df['Consequences of the attack'] = df['Consequences of the attack'].str.replace('murdered','murder')
df['Consequences of the attack'] = df['Consequences of the attack'].str.replace('physical attack','physical injury')
df['Consequences of the attack'] = df['Consequences of the attack'].str.replace('pregnent','pregnant')
df['Consequences of the attack'] = df['Consequences of the attack'].str.replace('dearth','death')
df['Consequences of the attack'] = df['Consequences of the attack'].str.replace('mantally ill','mentally ill')

In [48]:
df['Consequences of the attack'].unique()

array(['physical injury', 'mentally ill', 'murder', 'pregnant', 'death',
       'muder', nan], dtype=object)

In [49]:
df['Type of Attack'].unique()

array(['Child ', 'Gang', 'Opportunist', 'Child', 'Oppurtunist',
       'Opporunist', 'Marital', 'child', 'women', 'opportunist', 'gang',
       nan, 'Minor', '15', 'Gang '], dtype=object)

In [50]:
df['Type of Attack'] = df['Type of Attack'].str.lower()
df['Type of Attack'] = df['Type of Attack'].str.strip()

In [51]:
df[df['Type of Attack'] == 'women']

,Reference number,Description of Incidents,Type of Attack,Attempted or Raped,Who was it reported to,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
875,TW05LI57SH,43 years old Ranjit Thami was arrested by pol...,women,Rape,Police,physical injury,11/01/2020,Kathmandu,"27.724898979916542, 85.32441373802415",NaN

In [52]:
df['Type of Attack'] = df['Type of Attack'].str.replace('oppurtunist','opportunist')
df['Type of Attack'] = df['Type of Attack'].str.replace('opporunist','opportunist')
df['Type of Attack'] = df['Type of Attack'].str.replace('15','minor')
df['Type of Attack'] = df['Type of Attack'].str.replace('child','minor')
df['Type of Attack'] = df['Type of Attack'].str.replace('women','opportunist')

In [53]:
df['Type of Attack'].unique()

array(['minor', 'gang', 'opportunist', 'marital', nan], dtype=object)

In [54]:
df.rename(columns = {'Who was it reported to':'Reported To'}, inplace = True)

In [55]:
df['Reported To'] = df['Reported To'].str.lower()
df['Reported To'] = df['Reported To'].str.strip()

In [56]:
df[df['Reported To']=='his wife']

,Reference number,Description of Incidents,Type of Attack,Attempted or Raped,Reported To,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
202,GE82AS74UU,Police had arrested a man of around 35 year ol...,minor,Raped,his wife,physical injury,18/11/2015,Salyan,"28.442069207944435, 82.17124991675479",nepalpolice.gov.np

In [57]:
df['Reported To'].unique()

array(['victim father', 'police', 'victim', 'family', 'victim family',
       'neighbours', 'neighbors', 'victim mother', 'victim relatives',
       'in-law of victim', 'victims mother', 'victims family',
       'victim side', 'his wife', 'victimâ€™s relatives', 'victim raletive',
       'victim parents', 'victim raletives', 'victim relative',
       'victimâ€™s family', 'her fatherâ€™s sister', 'victimâ€™s mother',
       'victimâ€™s father', "victim's grandmother", "victim's family",
       'father-in-law', 'wife', "victim's mother", "victim's parents",
       "victims's mother", "victim's neighbors", "victim's son",
       "chairperson of women's security home", 'locals',
       "victim's brother", 'relatives', "victim's father",
       "victim's party", 'girl', "victim's side", 'victim aunt',
       "victim's relatives", 'victimâ€™s parents', 'victimâ€™s side',
       "victim's relative", "victim's uncle", nan, "victm's mother",
       "victim's famaly", 'insec and other organizations', "vctim's side",
       'victims father', "victim's side.", "victim girl's side",
       'victim parenst'], dtype=object)

In [58]:
df['Reported To'] = df['Reported To'].str.replace('victim father','father')
df['Reported To'] = df['Reported To'].str.replace('victim family','family')
df['Reported To'] = df['Reported To'].str.replace('neighbors','neighbours')
df['Reported To'] = df['Reported To'].str.replace('victim mother','mother')
df['Reported To'] = df['Reported To'].str.replace('victims family','family')
df['Reported To'] = df['Reported To'].str.replace('victim side','victim')
df['Reported To'] = df['Reported To'].str.replace('his wife','wife')
df['Reported To'] = df['Reported To'].str.replace('victimâ€™s relatives','relatives')
df['Reported To'] = df['Reported To'].str.replace('victim raletive','relatives')
df['Reported To'] = df['Reported To'].str.replace('victim raletives','relatives')
df['Reported To'] = df['Reported To'].str.replace('victim parents','parents')
df['Reported To'] = df['Reported To'].str.replace('victim relative','relatives')
df['Reported To'] = df['Reported To'].str.replace('victim relative','relatives')
df['Reported To'] = df['Reported To'].str.replace('victim relative','relatives')
df['Reported To'] = df['Reported To'].str.replace('her fatherâ€™s sister','relatives')
df['Reported To'] = df['Reported To'].str.replace('victimâ€™s mother','mother')
df['Reported To'] = df['Reported To'].str.replace('victimâ€™s father','father')
df['Reported To'] = df['Reported To'].str.replace('victim\'s grandmother','grandmother')
df['Reported To'] = df['Reported To'].str.replace('victim\'s family','family')
df['Reported To'] = df['Reported To'].str.replace('victim\'s mother','mother')
df['Reported To'] = df['Reported To'].str.replace('victim\'s parents','parents')
df['Reported To'] = df['Reported To'].str.replace('victims\'s mother','mother')
df['Reported To'] = df['Reported To'].str.replace('victim\'s neighbors','neighbours')
df['Reported To'] = df['Reported To'].str.replace('victim\'s son','son')
df['Reported To'] = df['Reported To'].str.replace('chairperson of women\'s security home','security home')
df['Reported To'] = df['Reported To'].str.replace('victim\'s brother','brother')
df['Reported To'] = df['Reported To'].str.replace('victim\'s father','father')
df['Reported To'] = df['Reported To'].str.replace('victim\'s party','party')
df['Reported To'] = df['Reported To'].str.replace('victimâ€™s parents','parents')
df['Reported To'] = df['Reported To'].str.replace('victm\'s mother','mother')
df['Reported To'] = df['Reported To'].str.replace('victim\'s famaly','family')
df['Reported To'] = df['Reported To'].str.replace('insec and other organizations','organizations')
df['Reported To'] = df['Reported To'].str.replace('victim\'s side','victim')
df['Reported To'] = df['Reported To'].str.replace('vctim\'s side','victim')
df['Reported To'] = df['Reported To'].str.replace('victims father','father')
df['Reported To'] = df['Reported To'].str.replace('victim\'s relatives','relatives')
df['Reported To'] = df['Reported To'].str.replace('victim\'s side.','victim')
df['Reported To'] = df['Reported To'].str.replace('victim girl\'s side','victim')
df['Reported To'] = df['Reported To'].str.replace('victim parenst','parents')
df['Reported To'] = df['Reported To'].str.replace('relativess','relatives')
df['Reported To'] = df['Reported To'].str.replace('victims mother','mother')
df['Reported To'] = df['Reported To'].str.replace('victim\'s neighbours','neighbours')
df['Reported To'] = df['Reported To'].str.replace('father-in-law','in-laws')
df['Reported To'] = df['Reported To'].str.replace('in-law of victim','in-laws')
df['Reported To'] = df['Reported To'].str.replace('victimâ€™s family','family')
df['Reported To'] = df['Reported To'].str.replace('victim.','victim')

C:\Users\Bishesh Kafle\AppData\Local\Temp\ipykernel_13940\3900718067.py:37: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Reported To'] = df['Reported To'].str.replace('victim\'s side.','victim')
C:\Users\Bishesh Kafle\AppData\Local\Temp\ipykernel_13940\3900718067.py:46: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Reported To'] = df['Reported To'].str.replace('victim.','victim')

In [59]:
df['Reported To'].unique()

array(['father', 'police', 'victim', 'family', 'neighbours', 'mother',
       'relatives', 'in-laws', 'wife', 'parents', 'grandmother', 'son',
       'security home', 'locals', 'brother', 'party', 'girl',
       'victimaunt', 'victims side', 'victims relative', 'victims uncle',
       nan, 'organizations'], dtype=object)

In [60]:
df['Attempted or Raped'].unique()

array(['Molesting', 'Attempted', 'Raped', 'Assulting ', 'Molesting ',
       'Sexually Abusing ', 'Assaulted ', 'Attemed', 'Attemped',
       'sexual assault ', ' sexually abusing ', ' sexually harassing',
       'molesting ', ' sexually abusing', 'sexually assaulting ',
       'sexually harassing', ' sexual voilance', 'Sexual Harrassment',
       'Molestation', 'Sexual abuse', 'Raped and killed', 'Rape', 'Both',
       nan, 'Sexually Abusing', 'Sexually Abused', 'Sexually harassing',
       'sexually Abusing', 'assaulting', 'Marital Rape',
       'Sexually Harassment', 'Assaulted', 'Minor', 'Sexually Assault ',
       'Raped ', 'Sexually abused', 'Sexually Assaulted',
       'Attempted rape', 'Sexually harassed', 'Sexually assaulted',
       'Harrassed', 'Attempted ', 'Abused', 'sexually assaulting',
       'Sexually assulted', 'ATtempted', 'Sexually assaulted '],
      dtype=object)

In [61]:
df['Attempted or Raped'] = df['Attempted or Raped'].str.lower()
df['Attempted or Raped'] = df['Attempted or Raped'].str.strip()

In [62]:
df['Attempted or Raped'].unique()

array(['molesting', 'attempted', 'raped', 'assulting', 'sexually abusing',
       'assaulted', 'attemed', 'attemped', 'sexual assault',
       'sexually harassing', 'sexually assaulting', 'sexual voilance',
       'sexual harrassment', 'molestation', 'sexual abuse',
       'raped and killed', 'rape', 'both', nan, 'sexually abused',
       'assaulting', 'marital rape', 'sexually harassment', 'minor',
       'sexually assault', 'sexually assaulted', 'attempted rape',
       'sexually harassed', 'harrassed', 'abused', 'sexually assulted'],
      dtype=object)

In [63]:
df[df['Attempted or Raped']=='sexual voilance']

,Reference number,Description of Incidents,Type of Attack,Attempted or Raped,Reported To,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
458,LC26FI16DH,A special team of police despatched to monitor...,opportunist,sexual voilance,police,physical injury,04/08/2017,Kathmandu,"27.727026303889943, 85.32372709254854",nepalpolice.gov.np

In [64]:
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('assulting','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('attemed','attempt')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually abusing','abuse')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('molesting','molestation')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('attemped','attempt')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually harassing','harassment')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually assaulting','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexual voilance','harassment')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexual harrassment','harassment')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexual abuse','abuse')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('raped and killed','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('rape','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually abused','abuse')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('assaulting','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually harassment','harassment')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('minor','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually assault','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually assaulted','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('attempted rape','attempt')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually harassed','harassment')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('harrassed','harassment')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('abused','abuse')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexually assulted','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('assultd','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('sexual assault','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('attempted assault','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('assaulted','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('assaultd','assault')
df['Attempted or Raped'] = df['Attempted or Raped'].str.replace('attempted','attempt')

In [65]:
df['Attempted or Raped'].unique()

array(['molestation', 'attempt', 'assault', 'abuse', 'harassment', 'both',
       nan, 'marital assault'], dtype=object)

In [66]:
df["Districts"].unique()

array(['Kathmandu', 'Siraha', 'Jhapa', 'Rautahat', 'Mahottari', 'sunsari',
       'Rupandehi', 'Morang', 'Sindhupalchowk', 'Khotang', 'Rukum',
       'Palpa', 'Lamjung', 'Gulmi', 'Kaverepalanchowk', 'Kaski', 'Banke',
       'Kavrepalanchock', 'Bara', 'Bhaktapur', 'Pyuthan',
       'Kaverepalanchok', 'Sarlahi', 'Bhojpur', 'Sunsari', 'Terhathum',
       'Dang', 'Syangja', 'Kailali', 'Kanchanpur', 'Gorkha', 'Dadeldhura',
       'Dhanusa', 'Kavrepalanchok', 'Panchthar', 'Sindhuli', 'Tanahu',
       'Udayapur', 'Makwanpur', 'Ilam', 'Rasuwa', 'Kapilvastu', 'Baglung',
       'Bardiya', 'Sindhupalchok', 'Jajarkot', 'Lalitpur', 'Dailekh',
       'Myagdi', 'Arghakhanchi', 'Taplejung', 'Dolakha', 'Nawalparasi',
       'Darchula', 'Salyan', 'Surkhet', 'Parsa', 'Parbat', 'Saptari',
       'Panchathar', 'Kalikot', 'Dhanusha', 'Chitwan', 'Mohattari',
       'Baitadi', 'Bajura', 'Nuwakot', 'Bajhang', 'Sunsary', 'Jumla',
       'Solukhumbu', 'Mugu', 'Dhading', 'Nawalparasi West',
       'Western Rukum', 'Rukum East', 'Birgunj', 'Kavre', 'Dhankuta',
       'Nawalparasi east', 'Doti', 'Rupendhi', 'Nawalparasi west',
       'Achham', 'Udhayapur', 'Hetauda', 'Rukum west', 'Okhaldhunga',
       'Terahathum', 'Madi', 'Tanahun', 'Ramechhap', 'Mustang',
       'Rukum West', 'Dolpa', 'Sankhuwasabha', 'Makawanpur', 'Chitawan',
       'Udaypur', 'Kathamandu', 'Sindupalchowk', 'Solukhumbhu',
       'Nawalparasi East', 'Rukum (West)', 'Syangya', 'Kapilbastu',
       'Kaplivastu', 'Accham', 'Rukun (Eastern)', 'Rolpa',
       'Rukum(eastern)', 'Bardia', 'Nawalpur', nan, 'Rupendehi', 'Bakya',
       'Sayanja', 'Ruoendehi', 'Sapatari', 'Bhojur', 'Sindhhupalchok',
       'Terathum', 'Humla', 'Pokhara', 'Kabhrepalanchok',
       'Sindhupalachok', 'Nawaparasi West', 'Sayangja', 'Udaipur',
       'Illam', 'Bardibas', 'Itahari', 'Taplegunj', 'Manang', 'parsa',
       'Sudurpachim', 'Lumbini', 'Pratappur', 'Tahanu',
       'Rukum West, Karnali', 'Dharan', 'Rampur, Palpa',
       'Gandaki, Parbat', 'Gandaki, Myagdi', 'Karnali, Dailekh',
       'Mades,Bara', 'Rupandhi', 'Kritipur', 'Pachthar', 'Sindhupalchwok',
       'Okheldunga', 'Tehrathum', 'Rupandahi', 'Sindhuplchowk',
       'Shankhuwasabha', 'Solukhubmu', 'Dolkha', 'Sindupalchok'],
      dtype=object)

In [67]:
df

,Reference number,Description of Incidents,Type of Attack,Attempted or Raped,Reported To,Consequences of the attack,Date of Incident,Districts,Geographical Region,Sources
0,CH14QV99NQ,An 18-year-old youth was arrested March 25 on ...,minor,molestation,father,physical injury,25/03/2013,Kathmandu,"27.7199745185167, 85.32344429728326",thehimalayantimes.com
1,XJ99BF74EC,Police had taken under control Hitman Shahi (4...,minor,attempt,police,physical injury,03/04/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
2,IG49WH92XY,Fourteen year old Devendra Rana and eleven yea...,gang,assault,police,physical injury,01/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
3,IS62NJ41RL,Police on 07 May arrested Dharmaraj Jamarkatte...,minor,assault,police,physical injury,07/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",nepalpolice.gov.np
4,ZP39BS50LY,Police on 08 May arrested Bhakta Bahadur Blon ...,opportunist,assault,police,physical injury,08/05/2013,Kathmandu,"27.7199745185167, 85.32344429728326",thehimalayantimes.com
...,...,...,...,...,...,...,...,...,...,...
2415,VQ02QJ16IA,One person has been arrested on charges of rap...,opportunist,assault,police,physical injury,14/06/2023,Lalitpur,"27.662405818404125, 85.32435296718468",nepalmonitor.org
2416,OS92RX27HN,"Baglung, a 17-year-old boy living in Nisikhola...",minor,assault,police,physical injury,09/07/2023,Baglung,"28.28119980900559, 83.58164488651326",nepalpolice.gov.np
2417,LW75CB63DB,"Jhapa, 31-year-old Dhan Kumar Limbu, resident ...",opportunist,assault,police,physical injury,07/02/2023,Jhapa,"26.577739181619766, 87.89718581504616",nepalpolice.gov.np
2418,KH48LW89IO,"Baglung, Police arrested 28-year-old Bimal Ham...",opportunist,assault,police,physical injury,12/07/2023,Baglung,"28.28104863825078, 83.58215987061996",nepalpolice.gov.np
2419,HH53FD93DS,Man arrested from Sankhuwasabha on the charge ...,opportunist,assault,police,physical injury,12/07/2023,Sankhuwasabha,"27.676079840209752, 87.30574864049214",nepalmonitor.org

In [68]:
df["Districts"]=df["Districts"].str.lower()
df["Districts"]=df["Districts"].str.strip()
df["Districts"]=df["Districts"].str.replace("kaverepalanchowk","kavrepalanchok")
df["Districts"]=df["Districts"].str.replace("sunsary","sunsari")
df["Districts"]=df["Districts"].str.replace("rupendhi","rupandehi")
df["Districts"]=df["Districts"].str.replace("terahathum","terhathum")
df["Districts"]=df["Districts"].str.replace("solukhubmu","solukhumbu")
df["Districts"]=df["Districts"].str.replace("tehrathum","terhathum")
df["Districts"]=df["Districts"].str.replace("terathum","terhathum")
df["Districts"]=df["Districts"].str.replace("rupandahi","rupandehi")
df["Districts"]=df["Districts"].str.replace("rupandhi","rupandehi")
df["Districts"]=df["Districts"].str.replace("sindupalchok","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindupalchowk","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindhupalachok","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindhhupalchok","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindhupalchok","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindhuplchwok","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindhuplchowk","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("sindhupalchwok","sindhupalchowk")
df["Districts"]=df["Districts"].str.replace("mohattari","mahottari")
df["Districts"]=df["Districts"].str.replace("ruoendehi","rupandehi")
df["Districts"]=df["Districts"].str.replace("rupendehi","rupandehi")
df["Districts"]=df["Districts"].str.replace("western rukum","rukum")
df["Districts"]=df["Districts"].str.replace("rukum west, karnali","rukum")
df["Districts"]=df["Districts"].str.replace("rukum \(west\)","rukum")
df["Districts"]=df["Districts"].str.replace("rukum west","rukum")
df["Districts"]=df["Districts"].str.replace("rukum east","rukum")
df["Districts"]=df["Districts"].str.replace("kabhrepalanchok","kavre")
df["Districts"]=df["Districts"].str.replace("kavrepalanchock","kavre")
df["Districts"]=df["Districts"].str.replace("kaverepalanchok","kavre")
df["Districts"]=df["Districts"].str.replace("kavrepalanchok","kavre")
df["Districts"]=df["Districts"].str.replace("bhojur","bhojpur")
df["Districts"]=df["Districts"].str.replace("sayangja","syangja")
df["Districts"]=df["Districts"].str.replace("sayanja","syangja")
df["Districts"]=df["Districts"].str.replace("panchathar","panchthar")
df["Districts"]=df["Districts"].str.replace("pachthar","panchthar")
df["Districts"]=df["Districts"].str.replace("tahanu","tanahu")
df["Districts"]=df["Districts"].str.replace("tanahun","tanahu")
df["Districts"]=df["Districts"].str.replace("udhayapur","udayapur")
df["Districts"]=df["Districts"].str.replace("udaypur","udayapur")
df["Districts"]=df["Districts"].str.replace("udaipur","udayapur")
df["Districts"]=df["Districts"].str.replace("ilam","illam")
df["Districts"]=df["Districts"].str.replace("kapilbastu","kapilvastu")
df["Districts"]=df["Districts"].str.replace("bardia","bardiya")
df["Districts"]=df["Districts"].str.replace("dailekh","dailekh")
df["Districts"]=df["Districts"].str.replace("taplegunj","taplejung")
df["Districts"]=df["Districts"].str.replace("dolkha","dolakha")
df["Districts"]=df["Districts"].str.replace("nawaparasi west","nawalparasi")
df["Districts"]=df["Districts"].str.replace("nawalparasi west","nawalparasi")
df["Districts"]=df["Districts"].str.replace("nawalparasi east","nawalparasi")
df["Districts"]=df["Districts"].str.replace("pratappur","nawalparasi")
df["Districts"]=df["Districts"].str.replace("sapatari","saptari")
df["Districts"]=df["Districts"].str.replace("chitawan","chitwan")
df["Districts"]=df["Districts"].str.replace("solukhumbhu","solukhumbu")
df["Districts"]=df["Districts"].str.replace("solukhubmu","solukhumbu")
df["Districts"]=df["Districts"].str.replace("shankhuwasabha","sankhuwasabha")
df["Districts"]=df["Districts"].str.replace("bakya","banke")
df["Districts"]=df["Districts"].str.replace("rampur, palpa","palpa")
df["Districts"]=df["Districts"].str.replace("gandaki, parbat","parbat")
df["Districts"]=df["Districts"].str.replace("gandaki, myagdi","myagdi")
df["Districts"]=df["Districts"].str.replace("karnali, dailekh","dailekh")
df["Districts"]=df["Districts"].str.replace("mades,bara","bara")
df["Districts"]=df["Districts"].str.replace("kritipur","kathmandu")
df["Districts"]=df["Districts"].str.replace("okheldunga","okhaldhunga")
df["Districts"]=df["Districts"].str.replace("mades,bara","bara")
df["Districts"]=df["Districts"].str.replace("birgunj","parsa")
df["Districts"]=df["Districts"].str.replace("hetauda","makwanpur")
df["Districts"]=df["Districts"].str.replace("pokhara","kaski")
df["Districts"]=df["Districts"].str.replace("itahari","sunsari")
df["Districts"]=df["Districts"].str.replace("lumbini","rupandehi")
df["Districts"]=df["Districts"].str.replace("dharan","sunsari")
df["Districts"]=df["Districts"].str.replace("bardibas","mahottari")
df["Districts"]=df["Districts"].str.replace("dhanusha","dhanusa")
df["Districts"]=df["Districts"].str.replace("madi","chitwan")

C:\Users\Bishesh Kafle\AppData\Local\Temp\ipykernel_13940\2300343643.py:25: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Districts"]=df["Districts"].str.replace("rukum \(west\)","rukum")

In [69]:
len(df['Districts'].unique())

85

In [70]:
df.dropna(inplace = True)

In [71]:
df = df.reset_index()
df = df.drop('index',axis = 1)

In [72]:
df.to_csv('cleandata.csv')